/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    UpDown: {
      address: "0xc5331b149244b678268fedba9fdd610c3a38e925",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_owner",
              type: "address",
              internalType: "address",
            },
            {
              name: "_usdcToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_swapRouter",
              type: "address",
              internalType: "address",
            },
            {
              name: "_ethFeed",
              type: "address",
              internalType: "address",
            },
            {
              name: "_btcFeed",
              type: "address",
              internalType: "address",
            },
            {
              name: "_clawdToken",
              type: "address",
              internalType: "address",
            },
            {
              name: "_weth",
              type: "address",
              internalType: "address",
            },
            {
              name: "_sequencerUptimeFeed",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BPS_DENOM",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BURN_ADDRESS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CANCEL_GRACE",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "FEE_USDC_WETH",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint24",
              internalType: "uint24",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "FEE_WETH_CLAWD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint24",
              internalType: "uint24",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_PAYOUT_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_PRICE_STALENESS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_SLIPPAGE_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_PAYOUT_BPS",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_PRICE_AGE_AT_BET",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SEQUENCER_GRACE_PERIOD",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "SETTLE_DELAY",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "acceptOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "betCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bets",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "betId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
            {
              name: "asset",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "direction",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "usdcAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "entryPrice",
              type: "int256",
              internalType: "int256",
            },
            {
              name: "settleAfter",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "entryRoundId",
              type: "uint80",
              internalType: "uint80",
            },
            {
              name: "payoutMultiplierBps",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum UpDown.BetStatus",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "btcFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "cancelExpiredBet",
          inputs: [
            {
              name: "betId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "clawdToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ethFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "fundHouse",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getBet",
          inputs: [
            {
              name: "betId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct UpDown.Bet",
              components: [
                {
                  name: "betId",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "player",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "asset",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "direction",
                  type: "uint8",
                  internalType: "uint8",
                },
                {
                  name: "usdcAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "entryPrice",
                  type: "int256",
                  internalType: "int256",
                },
                {
                  name: "settleAfter",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "entryRoundId",
                  type: "uint80",
                  internalType: "uint80",
                },
                {
                  name: "payoutMultiplierBps",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "status",
                  type: "uint8",
                  internalType: "enum UpDown.BetStatus",
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPendingBets",
          inputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPlayerBetIds",
          inputs: [
            {
              name: "player",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getPrice",
          inputs: [
            {
              name: "asset",
              type: "uint8",
              internalType: "uint8",
            },
          ],
          outputs: [
            {
              name: "",
              type: "int256",
              internalType: "int256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "housePool",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "maxBet",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "minBet",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "payoutMultiplierBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingOwner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "placeBet",
          inputs: [
            {
              name: "asset",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "direction",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "usdcAmount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "betId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "sequencerUptimeFeed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract AggregatorV3Interface",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "setLimits",
          inputs: [
            {
              name: "_minBet",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_maxBet",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "_payoutMultiplierBps",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "setSlippageBps",
          inputs: [
            {
              name: "_slippageBps",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "settle",
          inputs: [
            {
              name: "betId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minPayoutClawd",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "minBurnClawd",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "slippageBps",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "swapRouter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract ISwapRouter02",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "usdcToken",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract IERC20",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "weth",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdrawHouse",
          inputs: [
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "BetCancelled",
          inputs: [
            {
              name: "betId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "refundedUsdc",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BetPlaced",
          inputs: [
            {
              name: "betId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "player",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "asset",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "direction",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "usdcAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "entryPrice",
              type: "int256",
              indexed: false,
              internalType: "int256",
            },
            {
              name: "payoutMultiplierBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BetSettled",
          inputs: [
            {
              name: "betId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "status",
              type: "uint8",
              indexed: true,
              internalType: "enum UpDown.BetStatus",
            },
            {
              name: "payoutUsdc",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "clawdAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Deployed",
          inputs: [
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "usdcToken",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "clawdToken",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "weth",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "swapRouter",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "ethFeed",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "btcFeed",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "sequencerUptimeFeed",
              type: "address",
              indexed: false,
              internalType: "address",
            },
            {
              name: "initialMinBet",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "initialMaxBet",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "initialPayoutMultiplierBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "HouseFunded",
          inputs: [
            {
              name: "from",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newHousePool",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "HouseWithdrawn",
          inputs: [
            {
              name: "to",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "newHousePool",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "LimitsUpdated",
          inputs: [
            {
              name: "minBet",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "maxBet",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
            {
              name: "payoutMultiplierBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferStarted",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SlippageUpdated",
          inputs: [
            {
              name: "newSlippageBps",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "AmountZero",
          inputs: [],
        },
        {
          type: "error",
          name: "BetAmountOutOfRange",
          inputs: [],
        },
        {
          type: "error",
          name: "BetNotPending",
          inputs: [],
        },
        {
          type: "error",
          name: "HousePoolTooSmall",
          inputs: [],
        },
        {
          type: "error",
          name: "InsufficientHousePool",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidAsset",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidDirection",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidLimits",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPrice",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidPriceRound",
          inputs: [],
        },
        {
          type: "error",
          name: "InvalidSlippage",
          inputs: [],
        },
        {
          type: "error",
          name: "MinOutBelowFloor",
          inputs: [],
        },
        {
          type: "error",
          name: "NotAuthorized",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "PriceRoundNotAdvanced",
          inputs: [],
        },
        {
          type: "error",
          name: "ReentrancyGuardReentrantCall",
          inputs: [],
        },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [
            {
              name: "token",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SequencerDown",
          inputs: [],
        },
        {
          type: "error",
          name: "SequencerGracePeriodNotOver",
          inputs: [],
        },
        {
          type: "error",
          name: "StalePrice",
          inputs: [],
        },
        {
          type: "error",
          name: "TooEarlyToCancel",
          inputs: [],
        },
        {
          type: "error",
          name: "TooEarlyToSettle",
          inputs: [],
        },
        {
          type: "error",
          name: "ZeroAddress",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 44836164,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
